name: flutly
description: "Flutly is a modern and customizable Flutter library that offers a collection of flexible and user-friendly widgets and tools."
version: 1.0.0+22
homepage: https://github.com/codecores/flutly

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  internet_connection_checker_plus: ^2.5.1
  get: ^4.6.6
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.3
  yaml: ^3.1.2
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  flutter_bounceable: ^1.1.0
  flutter_animate: ^4.5.0
  blur: ^4.0.0
  vibration: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true